### ISSUE TITLE
AMD module loaded not called

### ISSUE THREAD

**Issue by goatsweater** [tbs-sct/gcconnex#125]
The foot.php, the AMD module loader (require) is never called.

**Comment by goatsweater** [comment]
See commit 22be8e717bb3f6ba66186fccd9bc0da45ca3aa14 for fix.

**Comment by Troy-Lawson** [comment]
@Phanoix is this still an issue?

**Comment by Phanoix** [comment]
looks like it's been merged in a while ago.
