### ISSUE TITLE
Side menu does not appear with WET4 theme enabled

### ISSUE THREAD

**Issue by smellems** [tbs-sct/gcconnex#128]
The side menu does not appear when we enable WET4.

Looking in the HTML I see this that the nav tag is doubled and that maybe causing it to not show up..

    <nav role="navigation" id="wb-sm" data-trgt="mb-pnl" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">
      <div>
        <div>
          <nav role="navigation" id="wb-sm" data-trgt="mb-pnl" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">
            ...

**Comment by Troy-Lawson** [comment]
@Phanoix is this still an issue?

**Comment by Phanoix** [comment]
It's working as intended by now at least.
