### ISSUE TITLE
Notification Email Messages Control Panel menu

### ISSUE THREAD

**Issue by 3lywa** [tbs-sct/gcconnex#133]
The "Notification Email Messages Control Panel" menu looks out of place when accessing "Notifications" tab under Home -> Settings -> Configure your tools

![image](https://cloud.githubusercontent.com/assets/3789862/13922724/ee82001e-ef53-11e5-990f-47f2a19b8644.png)

**Comment by Phanoix** [comment]
The notifications control panel should be showing up now on prod.
