### ISSUE TITLE
Display Issues with Featured Groups and Latest Wire Posts Sidebars

### ISSUE THREAD

**Issue by massierick** [tbs-sct/gcconnex#134]
If a group listed in the "featured group" sidebar does not have an icon assigned to the group, GCConnex seems to:

-  automatically create a blank image to go where a group icon would normally display, and
- displays the ALT text over top of the blank image.

As a result, you see the group name duplicated twice, with the alt text overflowing into the main Group Title.

I am not certain, but it may be an issue only with "closed groups". For open groups, even if they have no Image uploaded as an icon, they seem to display the default "heads" icon. 

![screenshot_2016-03-29-07-54-49](https://cloud.githubusercontent.com/assets/15625062/14112575/0f0009e0-f584-11e5-8479-6f060398a1c8.jpg)

**Comment by Phanoix** [comment]
Is this on production or pre-prod? I'm pretty sure this happens when there should be a thumbnail / image but it's missing from the data directory (which may be the case for some of the newer groups on non-production installations)

**Comment by massierick** [comment]
This is on the active live server (not pre-production). I haven't been able to find many instances of it, and it seems like it might be limited to closed groups (but I haven't found enough examples to confirm it yet). Also of note, I am using firefox - I only mention this since another issue I recently flagged was a firefox-specific bug.

**Comment by massierick** [comment]
Another firefox-specific issue - this time on the "Latest wire posts on GCconnex" sidebar. 
![gcconnex-issue](https://cloud.githubusercontent.com/assets/15625062/14214206/93289b74-f7f0-11e5-83b9-55d5bdbf048e.jpg)

**Comment by Phanoix** [comment]
Looks like it's been fixed.
