### ISSUE TITLE
Colorbox Modal Does Not Close Properly

### ISSUE THREAD

**Issue by massierick** [tbs-sct/gcconnex#135]
To replicate the issue, head to dashboard > click add widgets. 

The "close" text does not allow you to close the modal. You can only close the modal dialog by clicking outside the modal (according to the code, it seems to be related to the cboxwrapper dive area.)

div id="cboxWrapper" style="height: 770; width: 400x;">

    <div>
        <div id="cboxTopLeft" style="float: left;"></div>
        <div id="cboxTopCenter" style="float: left; width: 670px;"></div>
        <div id="cboxTopRight" style="float: left;"></div>
    </div>

Also of interest - if you remove "bottom:100%;" from the cboxclose class, the "close" text moves down the page, and then is able to be clicked on to close the modal. So there are some possible glitches between a number of CSS elements that might be causing this. 

#cboxClose {
    position: absolute;
    bottom: 100%;
    top: 8px;
    right: 20px;
    display: block;
    color: #444;
}

**Comment by Phanoix** [comment]
Interestingly enough, this seems to be a Firefox-specific bug.
