### ISSUE TITLE
wet4 skin cleanup - Split skin parts from the rest

### ISSUE THREAD

**Issue by Phanoix** [tbs-sct/gcconnex#175]
The parts that have nothing to do with the look, layout, etc of the site should not be in the skin mod, this task is to split them off into their own separate mod(s).

part of #174

**Comment by piet0024** [comment]
I'm brainstorming how to split up the mod. 

- Group Layout Mod: This will include the changes to the group layout, the addition of the cover photo, and the group ajax loading content
-Newsfeed mod
-Form Accessibility (we overwrite all of the forms created by mods for accessability)

Can anyone think of something else in the wet mod that shouldn't be there or should have it's own mod?

**Comment by piet0024** [comment]
Newsfeed mod in merge request tbs-sct/gcconnex#476

**Comment by Steph4104** [comment]
Splash page mod in merge request #483

**Comment by Steph4104** [comment]
Form accessibility in merge request tbs-sct/gcconnex#492

**Comment by piet0024** [comment]
Group layout mod in merge request tbs-sct/gcconnex#511
