### ISSUE TITLE
Streaming Wire

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#235]

**Comment by piet0024** [comment]
I feel like we should do some requirements gathering before proceeding with this project :)

**Comment by ToferC** [comment]
@piet0024 @pandurx - Can we please schedule the requirements gathering session for this.  A responsive app would be a big step towards (appearing like) a modern web application. :)

**Comment by Troy-Lawson** [comment]
Changing title to represent this is just for the wire. Will create new issue for news / activity feed when appropriate.
