### ISSUE TITLE
Delete unused files from main folder

### ISSUE THREAD

**Issue by smellems** [tbs-sct/gcconnex#280]
Some files that could be deleted.

- UPGRADE.TXT
- CODING.txt
- CONTRIBUTING.md
- GCconnex mods list.txt
- changed_files_list_phase1.txt
- changes_phase1.txt

Do we need to keep Composer or Grunt?

**Comment by Phanoix** [comment]
Composer does install most of the automated testing frameworks, I'll look into the Grunt one.

**Comment by smellems** [comment]
There is also the Docs folder.  I think that it's the Elgg Learning Website and Grunt is used to build it.
