### ISSUE TITLE
Notification - blog (even when unsubscribed)

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#303]
GCCON-259
Many users are reporting that they are receiving multiple notifications for blogs, even if they are not subscribed to the group.

**Comment by pandurx** [comment]
This issue may be related to the Minor Edit Issue (see #290)

**Comment by RimaSakr** [comment]
on Nov 23, a user reported receiving notifications when her colleagues accepted colleagues invitation from others . when she asked them if they published anything on the site, they said no , they just accepted some colleagues request : for exemple sonia tengelson received this message 
![capture](https://cloud.githubusercontent.com/assets/23101205/20753597/19c2650e-b6d5-11e6-9a5a-d1020c119dc8.PNG).  the issue might be related to #506 . thanks
