### ISSUE TITLE
Taran.Wasson@pco-bcp receive a notification wiht emply message.

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#307]
GCCON-256
From: GCconnex (TBS/SCT) [mailto:tbs.DoNotReply-NePasRepondre.sct@canada.ca] 
 Sent: October 21, 2016 2:04 PM 
 To: Wasson, Taran (PCO/BCP) 
 Subject: Your cell # 
 
 GCconnex 
 (Le français suit) 
 sent you a site message entitled '' 
 The content of the message is: 
 
 You can view or reply to this by clicking on this link: 
 Learn more about GCconnex notifications. Need help? Contact us. 
 To unsubscribe from these notifications, login to GCconnex and edit your notifications' settings. 
 vous a envoyé un message intitulé '' 
 Le contenu du message est le suivant : 
 
 Vous pouvez le consulter ou y répondre en cliquant sur le lien suivant: 
 Apprenez davantage au sujet des notifications de GCconnex. Besoin d’aide? Contactez-nous. 
 Pour vous désabonner de ces notifications, connectez-vous à GCconnex et modifiez vos paramètres de notifications. 
 - 
 
 email attached for reference

**Comment by Steph4104** [comment]
I think I fix this empty message in pull request #292

**Comment by Phanoix** [comment]
pr #292 is on production, closing the issue.
