### ISSUE TITLE
Federated Search - bug in results

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#311]
GCCON-241
Tried searching for a user (Francine Lemire) and received odd results in the federated search. One of the results received was "Edit Bookmark: ..." the description also included HTML coding (See attachment). I tried clicking on the link, it doesn't do anything. I then tried clicking on a link to group discussion that appeared in the results and it showed an error message saying the bookmark couldn't be identified. (See attachment). 
 I was able to replicate the bug.

**Comment by pandurx** [comment]
I sent an email to Rajeev to check that URL path /bookmarks/edit/ is filtered.

**Comment by pandurx** [comment]
The URL has been added to the GSA and is now resolved.
