### ISSUE TITLE
Denied Colleague Requests Persist

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#321]
GCCON-183
User claims that colleague request he has sent and that have been denied remain active / alive, resulting in the recipient getting multiple requests. User claims that the only way to stop this is to go into his colleague requests and manually cancel the request. Could you please test this and let me know if this is actually the case? As per our discussion, please keep this confidential until further notice. Thanks!

**Comment by piet0024** [comment]
I can't replicate this. 

When a user denies a request they can receive another request from the same user. Denying a request does not mean they will never get a request from that user again.

This may have also been an issue when we had users who friend request everyone and everyone as long as the "Request Colleague" link was there.
