### ISSUE TITLE
Issues with Forum Notification (Unsubscribed but notified)

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#328]
GCCON-133
From: multiple users 
 Msg: Joining the Job Seekers Group prompts users to receive notification every time there is new content i.e. New File. 
 
 Please see the attached.

**Comment by pandurx** [comment]
Receiving new notifications about new content being created (that is not related to Forums) is not an issue with the forums, the user must unsubscribe from the group itself.

Information in JIRA (comments and replies) does not reflect this issue.

**Comment by KevinChagnon** [comment]
User reports receiving Notices when new files are being posted in Job Seeker's group even after having unsubscribed from the Group.

User: Elvya.Gaudin2

**Comment by KevinChagnon** [comment]
Another user reporting same issue.  Has opted out of everything and unsubscribed from JobSeekers.
Still receiving notices.
User: Kelly.Donoghue


![notification after unsubcribing and opting out](https://cloud.githubusercontent.com/assets/23527358/21103274/c0d30046-c04f-11e6-9406-f913f2998e51.JPG)

**Comment by KevinChagnon** [comment]
Another user reporting same issue. 7 unwanted emails in one day.

![notification after unsubscribing](https://cloud.githubusercontent.com/assets/23527358/21818279/2fa3ca04-d735-11e6-93ff-1b0c4eb62b15.JPG)


Username: Lorraine Richer

**Comment by pandurx** [comment]
There was a push for fixes for this issue back in 2017-01-01 (see gcpedia changelog) is this issue still recurring? I have the forum (topic) listed under the respective group (in their notification settings) so they can unsubscribe for notification.

**Comment by pandurx** [comment]
@KevinChagnon 
I have manually cleaned up each of the affected users listed in this ticket:

Lorraine Richer
Kelly Donoghue
Elvya Gaudin
