### ISSUE TITLE
Account Validation - link in the email not opening

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#329]
GCCON-120
From: marwa.ebrahim@canada.ca 
 Msg: Hello, I created an account with GCconnex. An email was sent to me to validate my account but the link included in the email is not opening. Thank you 
 
 *Requested to the user to forward the email received.

**Comment by pandurx** [comment]
I did a small test on production..

1. Register with my tbs email
2. a-gcconnex sends me a validation email (with the correct link)
    b-gcconnex admin sends a validation email through admin panel (with correct link)
3. Select the link in the email, directs me to GCconnex and validates my account + logs in
