### ISSUE TITLE
user is not able to creat an RSS feed for a page on GCconnex

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#338]
Brian.Williamson@hc.gc.ca is unable to have https://gcconnex.gc.ca/activity 
 this page part of his RSS feed, email is attached for reference. 
 thanks,

**Comment by Troy-Lawson** [comment]
review

**Comment by Phanoix** [comment]
The rss feed / view is still there, we just need to add a link to it (.../activity?view=rss) if we decide it's needed, otherwise we can provide this information to whoever wants the RSS feed (they just need to add ?view=rss in the address bar).
