### ISSUE TITLE
Custom widget - impossible to keep link

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#344]
GCCON-171
While creating custom widgets... we have the option of adding a link to the title. Unfortunately, the link doesn't seem to "stay". Once you input a link, it disappear once your refresh the page (and when you look at the code... the link is still there,..but not active).

**Comment by pandurx** [comment]
This is fixed, I'll double check in production..

**Comment by pandurx** [comment]
Tested on production, no longer an issue
