### ISSUE TITLE
Department/Agency dropdown defaults to Western Economic Diversification

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#346]
GCCON-156
BUG: Your Department/Agency dropdown defaults to Western Economic Diversification instead of the blank line. 
 
 Sent top NRC

**Comment by Phanoix** [comment]
This was fixed (removed attempt to auto-detect department) a while ago and now (#461, #478) should be defaulting to the correct department. We will see if production will behave the same way as everything else.
