### ISSUE TITLE
Tables created with Rich Text editor are not visible

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#365]
GCCON-45
Tables are no longer visible 
 https://gcconnex.gc.ca/pages/view/4255786/presentation-tracking-rapport-sur-les-presentations

**Comment by Troy-Lawson** [comment]
proposal

**Comment by Phanoix** [comment]
I have looked into this previously and implemented a css class whitelist which currently only includes 'table' and 'row' (https://github.com/tbs-sct/gcconnex/blob/gcconnex/mod/htmlawed/start.php#L112), for now users can add the table class to their tables to at least get some lines in their tables.
