### ISSUE TITLE
Accents n'apparaissent pas correctement dans le sujet d'un message

### ISSUE THREAD

**Issue by PhilAndrecheck** [tbs-sct/gcconnex#377]
Le titre est bon: «Delphine Renié liked your wire post | Delphine Renié a aimé votre message sur le fil»
mais le sujet d'un message lit comme suit : «Delphine ReniÃ© liked your wire post | Delphine ReniÃ© a aimÃ© votre message sur le fil»

**Comment by pandurx** [comment]
There's some issues with sending notification in-site

**Comment by pandurx** [comment]
@PhilAndrecheck Is this still recurring? The last update should have (maybe) fixed this.

**Comment by PhilAndrecheck** [comment]
Hi @pandurx, yes, just got a message with the subject like this:

-----Original Message-----
From: GCpedia [mailto:tbs.DoNotReply-NePasRepondre.sct@canada.ca] 
Sent: December 1, 2016 12:47 PM
To: Andrecheck, Philippe
Subject: =?UTF-8?Q?GCpedia=20page=20Objectif=202020/ChampionsF/mise=20=C3=A0=20jour=20d=C3=A9cembre=202016/Agence=20de=20d=C3=A9veloppement=20=C3=A9conomique=20du=20Canada=20pour=20les=20r=C3=A9gions=20du=20Qu=C3=A9bec=20has=20been=20changed=20by=20Frederique.R...

Dear Philippe.andrecheck,

The GCpedia page Objectif 2020/ChampionsF/mise à jour décembre
2016/Agence de développement économique du Canada pour les régions du
Québec has been changed on 1 December 2016 by Frederique.Roy-lavoie1, see
http://www.gcpedia.gc.ca/wiki/Objectif_2020/ChampionsF/mise_%C3%A0_jour_d%C3%A9cembre_2016/Agence_de_d%C3%A9veloppement_%C3%A9conomique_du_Canada_pour_les_r%C3%A9gions_du_Qu%C3%A9bec
for the current revision.



See
http://www.gcpedia.gc.ca/gcwiki/index.php?title=Objectif_2020/ChampionsF/mise_%C3%A0_jour_d%C3%A9cembre_2016/Agence_de_d%C3%A9veloppement_%C3%A9conomique_du_Canada_pour_les_r%C3%A9gions_du_Qu%C3%A9bec&diff=next&oldid=1713614
to view this change.

See
http://www.gcpedia.gc.ca/gcwiki/index.php?title=Objectif_2020/ChampionsF/mise_%C3%A0_jour_d%C3%A9cembre_2016/Agence_de_d%C3%A9veloppement_%C3%A9conomique_du_Canada_pour_les_r%C3%A9gions_du_Qu%C3%A9bec&diff=0&oldid=1713614
for all changes since your last visit.

Editor's summary:  -  

Contact the editor:
mail:
http://www.gcpedia.gc.ca/wiki/Special:EmailUser/Frederique.Roy-lavoie1
wiki: http://www.gcpedia.gc.ca/wiki/User:Frederique.Roy-lavoie1

There will be no other notifications in case of further activity unless
you visit this page. You could also reset the notification flags for all
your watched pages on your watchlist.

			 Your friendly GCpedia notification system

**Comment by Phanoix** [comment]
That one is from GCpedia, I'll have to take a look at it in a later sprint. Should be made into a separate issue in https://github.com/tbs-sct/gcpedia/issues.

**Comment by PhilAndrecheck** [comment]
Sorry Ilia. Reported in GCpedia section.
