### ISSUE TITLE
The label that has the number of Shares is missing a space in French

### ISSUE THREAD

**Issue by smellems** [tbs-sct/gcconnex#415]
I noticed this on the wire, but it seems to be everywhere.  When something has been shared, the number of shares appears next to share icon.  In english it would say "21 Shares", but in French "21Partages", no space.

![21partages](https://cloud.githubusercontent.com/assets/2353299/19941717/a87e4eb8-a107-11e6-81e5-645f90afadc4.PNG)

**Comment by Steph4104** [comment]
Pull request tbs-sct/gcconnex#416
