### ISSUE TITLE
Forums subscription

### ISSUE THREAD

**Issue by pandurx** [tbs-sct/gcconnex#454]
Forum subscription inconsistencies with notifications (posting topics and posting comments)

**Comment by pandurx** [comment]
userA- subscribe (most outer) forum
userB- post topic under forum (most inner)
userA- receives notification with no subject

--

userA- subscribe forum topic
userB- post comment in forum topic
userA- receives x2 notifications (with/out subject)

**Comment by pandurx** [comment]
subscription to forum seems to be working correctly in local

**Comment by pandurx** [comment]
@ethanWallace @piet0024 can you guys take a look with the subscription on the forums? I found inconsistencies between production and my local (github) :confused:

**Comment by piet0024** [comment]
I tested both of those test cases on my local environment and on preprod. It seems to be working as intended. I get 1 notification with a subject line. 

I also get notified on the user that created the content that I created content, that might not be a part of this bug though.

Is this still not working on prod? Perhaps some files haven't gone up.

**Comment by pandurx** [comment]
The last time i checked, both users (recipient and creator) would receive notification for one single action. I think production may need to be updated with the module on Github.

**Comment by pandurx** [comment]
- Files between production/preprod and local are all identical

When you're friends with another user you get additional notifications, this is now patched and will only receive one notification.
