### ISSUE TITLE
Simplified sign-on to GCpedia redirects to GCconnex newsfeed

### ISSUE THREAD

**Issue by PhilAndrecheck** [tbs-sct/gcconnex#472]
When signing in to GCpedia using the simplified sign-on, after entering credentials and clicking "remember me" and loging in, it navigates to the GCconnex news feed instead of GCpedia.

https://gcconnex.gc.ca/saml/idp_login?ReturnTo=http%3A%2F%2Fgcconnex.gc.ca%2Fsimplesaml%2Fmodule.php%2Fauthelgg%2Fresume.php%3FState%3D_89028a77f82acfa7b00aa68eb72765264b137c660a%253Ahttp%253A%252F%252Fgcconnex.gc.ca%252Fsimplesaml%252Fsaml2%252Fidp%252FSSOService.php%253Fspentityid%253Dhttp%25253A%25252F%25252Fwww.gcpedia.gc.ca%25252Fsimplesaml%25252Fmodule.php%25252Fsaml%25252Fsp%25252Fmetadata.php%25252Felgg-idp%2526cookieTime%253D1479232601%2526RelayState%253Dhttp%25253A%25252F%25252Fwww.gcpedia.gc.ca%25252Fwiki%25252FMain_Page

**Comment by Troy-Lawson** [comment]
+1
