### ISSUE TITLE
empty site message

### ISSUE THREAD

**Issue by LemieuxGen** [tbs-sct/gcconnex#474]
I am receiving empty site messages. I also get many empty notifications, but this is affecting site messages as well. 
![site message - empty](https://cloud.githubusercontent.com/assets/15378977/20318283/a05f6782-ab37-11e6-8232-defe03fd9b87.JPG)

**Comment by LemieuxGen** [comment]
The site message was sent November 4th, after the bug release that was suppose to fix this bug.

**Comment by Troy-Lawson** [comment]
+1 this is great

**Comment by Steph4104** [comment]
Already fix in prod
