### ISSUE TITLE
Opportunities Platform - Error in visualizing stacked graph by program area

### ISSUE THREAD

**Issue by ToferC** [tbs-sct/gcconnex#500]
One field of the stacked graph is lacking a tag - bottom of the graph - dark blue.  Probably "Other".

**Comment by lucbelliveau** [comment]
Ready to be tested in #577

**Comment by ToferC** [comment]
The Program Area looks great, but I think the "Other" in Opportunity Type is supposed to be "Micro-mission".  Can we please make this change back and get it on production quickly?  Thanks!

There isn't an "Other" option in the location field either.  Not positive about "Reason to Decline".

**Comment by lucbelliveau** [comment]
Ready to be tested, again in #598 

I added a check to make sure the label is actually blank before replacing it with "Other".

**Comment by ToferC** [comment]
Thanks! 

Troy - can we validate and merge this pull request?

**Comment by lucbelliveau** [comment]
Hold off on merging this; now that I have data I can see the true cause of the problem...

**Comment by lucbelliveau** [comment]
New fix pushed

**Comment by ToferC** [comment]
Verified fixed in pre-prod.
