### ISSUE TITLE
Search queries are giving "Edit this page" results

### ISSUE THREAD

**Issue by LemieuxGen** [tbs-sct/gcconnex#507]
When searching GCconnex (GSA), the results I get are all "Edit this page". See attached screen shot.
![capture_search results_edit this page](https://cloud.githubusercontent.com/assets/15378977/20573008/d8486262-b17b-11e6-93d3-c52856824b81.JPG)

**Comment by pandurx** [comment]
Site had been re-crawled with the new rule to exclude /pages/edit/...

**Comment by Troy-Lawson** [comment]
checked in prod and confirmed
