### ISSUE TITLE
Migration to NGINX to improve speed?

### ISSUE THREAD

**Issue by gabrielcossette** [tbs-sct/gcconnex#521]
Has a future migration to NGINX to improve speed has been considered in the roadmap?
NGINX is known to be very fast and is very popular nowadays.

I understand that this would mean installing a third party package that would not be covered by the service agreement of the OS provider (Red Hat for example). However, the NGINX company do offer commercial support if we need it: https://www.nginx.com/support/

Anyway, I'm just saying the option should be carefully assessed because it could potentially greatly benefit the user experience.

**Comment by Troy-Lawson** [comment]
We have looked at NGINX briefly in the past. We are currently trying to improve our overall system architecture, focusing mostly on hardware for now. We hope to have a load balanced solution in the near future which may also see several key services broken off onto individual servers. We hope that this new configuration can greatly improve our speed and capacity going forward.

I suspect that following that we will eventually look into improving things from the software side as well. Things like NGINX, alternative databases, and just configuration tweaks will probably happen there.

Thank you for your question, I hope i have answered it your satisfaction. 
I will close the issue
