### ISSUE TITLE
Identify content avaialble in other language

### ISSUE THREAD

**Issue by smellems** [tbs-sct/gcconnex#522]
There is new functionality that allows users to create content (Discussions, blogs, ..) in both French and English.  Content will only be displayed in the language you are using for GCconnex.  But there is no way to know if the content is available in the other language.

I use GCconnex in English, but if someone wrote a blog in French and translated it to English, I would rather read it in French.  There should be an indicator that content is available in the other language and a way to switch.  Ideally without changing the language of the whole site.

**Comment by piet0024** [comment]
Let me know if you need any help with this :D
