### ISSUE TITLE
Changes not saving when Editing description of Opportunity

### ISSUE THREAD

**Issue by KevinChagnon** [tbs-sct/gcconnex#523]
System is not saving changes when a user Edits the description of an Opportunity in the "Career ConneXions Opportunities Platform - BETA"

In **Opportunity view**, user clicks on "Edit" at the bottom of the page
Changes are made to the **Bilingual description of opportunity**
User clicks on "Save" at the bottom of the page
The following message is displayed at the top of the page: "_Your changes to the opportunity 'Name of Opportunity' have been saved_".
User is still in Edit mode and the changes do not show in the **Bilingual description of opportunity** 

I obtained the same results when attempting to edit the users **Bilingual description of opportunity**

**Comment by lucbelliveau** [comment]
Ready to be tested in PR #576
