### ISSUE TITLE
French accents displayed as other caracters in User's name when viewing messages/notifications

### ISSUE THREAD

**Issue by KevinChagnon** [tbs-sct/gcconnex#524]
When a message is opened (from the inbox or sent messages) or a notification, the French accent a user's name and/or last name is replaced with other characters (see attached screen shot). Note that this is ONLY occurring in the page where the message is displayed, not in the page where the list of messages or notifications are displayed (ex: inbox); it's fine in the list pages

![gcconnexaccentissue](https://cloud.githubusercontent.com/assets/23527358/20608901/44df831e-b254-11e6-8d55-402c2fa667b3.jpg)
.

**Comment by smellems** [comment]
Maybe related to #285
