### ISSUE TITLE
Prototype API to update user profile information

### ISSUE THREAD

**Issue by smellems** [tbs-sct/gcconnex#525]
It should not update any information for now.  But show how we want to receive the information?  GET, POST, JSON, ..

We need some type of authentication, possibly with an API key.

It will be a starting point for the discussion with the GCIP team on the API specification.

**Comment by Troy-Lawson** [comment]
There is another item in the pipes with MyGCHR looking to push information into group(s). A method of authentication will have to be developed for that anyway.
The API framework has authentication built in, it is just a matter of us setting it up. There has, up to now, never been a need for it so it has never been integrated.

http://learn.elgg.org/en/2.0/guides/web-services.html
