### ISSUE TITLE
Opportunities Platform - Ability to share to more than one user from Find/Member Search results

### ISSUE THREAD

**Issue by ToferC** [tbs-sct/gcconnex#528]
As an opportunity creator, I want to be able to go down the list of members and offer opportunities to more than one user without having to re-run the search.  Options for resolution: check-box beside members and a single share opportunity button, ability to click "Share Opportunity" button and remain on search results page.

**Comment by lucbelliveau** [comment]
FYI This is done and submitted however github is not letting me create the PR... I also don't see the commit referenced here; I suspect github is just being slow updating caches or something.

For reference, here is the relevant commit: 967bf32fe2c71392681c53c4c9c9da867670a75c

I will try to submit a PR tomorrow.

**Comment by ToferC** [comment]
@lucbelliveau - Were you able to get the PR working?

**Comment by ToferC** [comment]
@lucbelliveau - Current functionality bumps user to top of page after sharing opportunity.  This means as a user, I:
* Scroll down to person I want to share opportunity with
* Click share opportunity
* Scroll back down to where I last shared opportunity
* Start looking at people again.
* Repeat

Can we adjust so that the user maintains their current vertical location after clicking the "Share Opportunity"?

Thanks!

**Comment by lucbelliveau** [comment]
@ToferC On my system vertical alignment stays the same...   I suspect the caches were not flushed; or a local cache issue in the browser...

**Comment by ToferC** [comment]
K. Thanks @lucbelliveau. We'll  check it out on production.
