### ISSUE TITLE
Page not found after login

### ISSUE THREAD

**Issue by smellems** [tbs-sct/gcconnex#541]
When logging in I get a 
> Page not found. Sorry. We could not find the page that you requested.

The network log show a 404.  Clicking on Newsfeed or other links is working.

The URL looks like it's not redirecting, it stays on https://gcconnex.gc.ca//simplesaml/saml2/idp/SSOService.php?spentityid=http://www.gcpedia.gc.ca/gcwiki/simplesaml/module.php/saml/sp/metadata.php/elgg-idp&RelayState=https://gcconnex.gc.ca/

## Steps to reproduce
- goto login page
- login
- get error

## Expected results
- newsfeed

**Comment by Troy-Lawson** [comment]
This issue is due to a quirk of the apache configuration. Have modified the code to address the issue
