### ISSUE TITLE
Cannot Edit first Work Experience entry

### ISSUE THREAD

**Issue by KevinChagnon** [tbs-sct/gcconnex#543]
When user clicks on edit to update work experience, the first entry available for editing is the second work experience entry seen on her profile.  see attached.

User: Joymosk

![work experience - edit](https://cloud.githubusercontent.com/assets/23527358/20718515/fd4c2e22-b626-11e6-9bf9-83769e868000.jpg)
![work experience - profile](https://cloud.githubusercontent.com/assets/23527358/20718514/fd43c6ec-b626-11e6-8da6-15e12419bcd6.jpg)

**Comment by KevinChagnon** [comment]
This problem seems to remain existent.
User's first Work experience on list is "Manager, Outreach and Engagement" but when we click on Edit, we are only able to Edit as of the second entry on the list which is "Manager, Outreach, Engagement, User Support, Content"

**Comment by Steph4104** [comment]
Have you test on Preprod? It's not on prod yet.
