### ISSUE TITLE
Missing "Embed Content" option when creating Events

### ISSUE THREAD

**Issue by KevinChagnon** [tbs-sct/gcconnex#560]
User reports that the "Embed Content" button/option is no longer available when creating an event.  This option was available in the past (at least in June 2016)

Link to event with embedded content: https://gcconnex.gc.ca/event_calendar/view/20341457/nsc-meeting-rencontre-du-cnd

can also be seen in attached pic
![embed content - event](https://cloud.githubusercontent.com/assets/23527358/20846879/b265a5da-b899-11e6-87df-9207339147fc.JPG)

**Comment by Steph4104** [comment]
Embed content is back on prod
