### ISSUE TITLE
micro-sized Mental health badge

### ISSUE THREAD

**Issue by PhilAndrecheck** [tbs-sct/gcconnex#571]
Mental health badge appears stretched and covers 90% of micro-size profile pic (e.g. for skills endorsements.)
![mhb](https://cloud.githubusercontent.com/assets/22220521/20897909/47dc0118-baf2-11e6-9e95-885c0e94d6e0.PNG)

As of Jan 4, still displays like this:

![small badge](https://cloud.githubusercontent.com/assets/22220521/21656057/7b6b1654-d28a-11e6-833d-5791e26292b0.PNG)

**Comment by Troy-Lawson** [comment]
may be related to tbs-sct/gcconnex#586
