### ISSUE TITLE
Mental Health badge alignement on avatar in groups when adding discussion

### ISSUE THREAD

**Issue by PhilAndrecheck** [tbs-sct/gcconnex#586]
When you click "discussions" from this group gcconnex.gc.ca/groups/profile/18274947/deliverology, avatar appears and the badges are out of proportion and misaligned (viewed on BlackBerry Q10). 

![img_20161208_163411](https://cloud.githubusercontent.com/assets/22220521/21029005/b106de90-bd65-11e6-92a4-163a52e7e6c3.png)

**Comment by Troy-Lawson** [comment]
may be related to tbs-sct/gcconnex#571

**Comment by PhilAndrecheck** [comment]
Hey @ethanWallace, just noticed this while reading a blog post:
![lastestcomments](https://cloud.githubusercontent.com/assets/22220521/21274616/21da8522-c397-11e6-9538-a05e98502349.png)

**Comment by ethanWallace** [comment]
Fixed with PR #592
