### ISSUE TITLE
Opportunities Platform > Find Members > Advanced > Opt in field is missing options

### ISSUE THREAD

**Issue by ToferC** [tbs-sct/gcconnex#595]
In the advance find for candidates; in the “opt in field” not all opportunities appear – can we add the assignments, secondments, deployments to that list too?

**Comment by lucbelliveau** [comment]
Looking at the opt-in form, I see the following types missing:
- Assignment / Secondment Seeker
- Assignment / Opportunity Creator
- Deployment Seeker
- Deployment Opportunity Creator
- Job Rotation Seeker
- Skill Sharing Opportunity Creator

@ToferC Can you confirm you would like to see all 6 of these added to the advanced filter?

Thanks

**Comment by ToferC** [comment]
Can we filter creator / seeker separately in *all* categories?

One future change were looking at is splitting opportunities into "seeking" and "offering" streams to improve the UX and simplify finding what they are looking for. 

Otherwise - confirmed.

**Comment by lucbelliveau** [comment]
Ready to be tested in #613

**Comment by lucbelliveau** [comment]
@ToferC Sounds like a new feature request; I suggest we create a new issue to split this up so we can get this bug fix into prod.

Regarding your question; yes we could change it however you like... maybe add a "* creator" and "* seeker" option?  Not sure what to call them though...

**Comment by ToferC** [comment]
Makes sense. I'll grab the text and create the issue. Thanks, Luc.

**Comment by ToferC** [comment]
This fix is ready for pre-prod & testing.  Thanks, @lucbelliveau
