### ISSUE TITLE
My Department Activity Tab does not show all activity

### ISSUE THREAD

**Issue by smellems** [tbs-sct/gcconnex#605]
On the Activity page there is a tab that should allow you to see activity from GCconnex members in your department, but not all activity is there.

https://gcconnex.gc.ca/activity_tabs/mydept/

This is probably because of the way the department is saved now that some departments are moving to @canada.ca emails.

**Comment by Phanoix** [comment]
The activity by department tab works off the users' selected department, so the most likely case here is that the users' who have yet to set their department are the ones not showing up.
Can I get some examples of missing activity to make sure that this is the case as opposed to an actual bug?

**Comment by smellems** [comment]
I can't test this right now, but I think people that have their department set to the same as mine are not showing up and others are..  Maybe there are different ways to set your department.  I never synced with GEDS..  I will confirm tomorrow morning.

**Comment by smellems** [comment]
Yes If I look this morning, on the news feed, I see that some of my colleagues from TBS have posted to the wire and commented on discussions.  I can see them also on the All and Colleague Activity tabs.  The My department and Other depts don't have everyone and only shows activity 18 hours ago..  The users that are shown are from TBS..
