### ISSUE TITLE
Missing GCConnex tools (icons) in IE 11

### ISSUE THREAD

**Issue by KevinChagnon** [tbs-sct/gcconnex#611]
GCConnex tools do not show on IE 11. Firefox 50.0.2 shows them.  see attached pic
![browser choice on gcconnex](https://cloud.githubusercontent.com/assets/23527358/21190522/14759384-c1f0-11e6-9f27-cf5d2f636ad7.png)

**Comment by piet0024** [comment]
There is an issue in some departments where their IE security settings are not letting the icon font download. All of the icons on GCconnex are part of a font that IE does not download for certain departments. 

Users from that department will need to ask their IT help desk to whitelist GCconnex and the fonts it downloads for IE. This security setting seems to only be in IE and not firefox, and the user will probably not have access to change the IE security settings without their IT help desk.
