### ISSUE TITLE
User received @mention notification e-mail destined for another user

### ISSUE THREAD

**Issue by KevinChagnon** [tbs-sct/gcconnex#626]
User: Katherine.Arsenault  (katherine.arsenault@pwgsc.gc.ca)

Received an @mention notification e-mail destined for another user.
Metion was @Katherine snow

see attached

[Email notification sent to wrong person.pdf](https://github.com/tbs-sct/gcconnex/files/661349/Email.notification.sent.to.wrong.person.pdf)

**Comment by Steph4104** [comment]
Take a look at the database and both information is fine.
Take a look at the discussion and the right name is selected.

I can't replicate the bug... I don't know what that can be.
