### ISSUE TITLE
Adding Related Groups - Scroll bar keeps jumping to top of list when searching groups

### ISSUE THREAD

**Issue by KevinChagnon** [tbs-sct/gcconnex#642]
"I can enter a search term in the related groups dialogue and a list appears bellow. however when I stop scrolling the list jumps back to the top. If I narrow the selection down to one group and I click on it the number is added to the dialogue box but then the actual related group loads. To counteract this I then copy the group ID from the URL, cick on "back" then paste the number and click add. "

**Comment by Troy-Lawson** [comment]
duplicate of tbs-sct/gcconnex#638 will close and keep other one active
