### ISSUE TITLE
Micro-mission participant alert subject bug

### ISSUE THREAD

**Issue by PhilAndrecheck** [tbs-sct/gcconnex#648]
I offered a micro-mission to an applicant and when she accepted, I got an alert title Participant Name Subject: Participating in 'Participant Name' ... instead of the title of the micro-mission:
![micromission](https://cloud.githubusercontent.com/assets/22220521/21645487/1ff9efb8-d260-11e6-8b01-28f7031e7e24.PNG)

**Comment by Phanoix** [comment]
I have a fix for the subject line bug, but is this being sent to the right user? the wording makes it seem like it should be going to the participant and not the creator.

**Comment by PhilAndrecheck** [comment]
Here's some new text for the opportunity creator. @LemieuxGen, do you agree?

EN:
[Participant name] has accepted your offer to participate in [Opportunity name{hyperlinked}].

FR:
[Participant name] a accepté votre offre de participer dans [Opportunity name{hyperlinked}].

**Comment by LemieuxGen** [comment]
@PhilAndrecheck : Look good!

**Comment by Phanoix** [comment]
What should the subject be? something along the lines of
[Participant name] is now participating in [Opportunity name]
or
[Participant name] has accepted your offer
