### ISSUE TITLE
Group Event Clalendar Widget: Links to personal calendar when trying to add event through widget

### ISSUE THREAD

**Issue by KevinChagnon** [tbs-sct/gcconnex#654]
When clicking on Event Calendar Widget within a Group and then on "Add Event", this defaults to the users personal event calendar and has an option to add the event to a group calendar once the event has been created and saved.
Current work around is to click on "More" on the group's main page, then "Events" ...this will default to the Group Calendar.
Seems to be a broken link to the Event Calendar Widget within a Group that redirects the user to their personal event calendar.

**Comment by Steph4104** [comment]
Should be! Have not tested yet

**Comment by Steph4104** [comment]
Just tested and it work fine for me.
