### ISSUE TITLE
Filtering search results by selcting only "Files" displays no results even if files Tagged with search term

### ISSUE THREAD

**Issue by KevinChagnon** [tbs-sct/gcconnex#666]
Clicking on a tag brings us to everything on all departments, however, when we try and filter for files with the tag nothing appears. It seems as though files are not registering.

Example: https://gcconnex.gc.ca/file/view/20224442/table-test

This files is tagged with "Test", when filtering a search for "Test" to only "Files" the search produces No Results.

**Comment by pandurx** [comment]
for some reason the GSA is not crawling the files properly, resulting in no files were indexed

**Comment by pandurx** [comment]
emailed Rajeev, waiting for a response.
