### ISSUE TITLE
GSA results to display title and description in same language (related to language split)

### ISSUE THREAD

**Issue by LemieuxGen** [tbs-sct/gcconnex#685]
As a frequent user, when I search for content (where the language of the content has been split in English and French), I need the GSA search result to display the title and description in the same language so that I can find what I'm looking for quicker and in my language of choice.

ex: I search "OutilsGC" in the GSA (GCconnex), the results show me content with "GCTools" as the title, and a French description (see screen shot).
![gsa resutls - language split](https://cloud.githubusercontent.com/assets/15378977/21986815/efc69684-dbce-11e6-8075-04e2c9fa80e5.JPG)

**Comment by pandurx** [comment]
when searching for a term in the federated search window, the result set shall now display both english and french

**Comment by pandurx** [comment]
@LemieuxGen as discussed, this card will need to be broken down to two cards (searching groups and filtering which group)

**Comment by LemieuxGen** [comment]
@pandurx I removed the information about the group search issue - I'll create a new ticket for that. Thanks.
