### ISSUE TITLE
Add Widgets: Ensure the top navigation search bar remains visible when users scroll down the Add Widgets page. 

### ISSUE THREAD

**Issue by Phanoix** [tbs-sct/gcconnex#71]
Ensure the top navigation search bar remains visible when users scroll down the Add Widgets page.

**Comment by pandurx** [comment]
The patch for this issue causes problem when viewing content that is larger than the screen size.
When you try to create new discussion topic, then user selects "embed content" the lightbox gets cut off at the bottom portion, user cannot see the save option. Currently, the temporary solution is to zoom out (70%).
