### ISSUE TITLE
privacy settings for "Skills" and avatar - request from deputy CIO

### ISSUE THREAD

**Issue by PhilAndrecheck** [tbs-sct/gcconnex#731]
@Troy-Lawson, related to #730, another request from the deputy CIO:
Add the ability to change the privacy settings for "Skills" and avatar in users' GCconnex profiles, so they can chose if it can be seen by "All public servants", "Users logged in to GCconnex only" or "Only me."

**Comment by Troy-Lawson** [comment]
at this time i am not sure it is possible to put a privacy setting on the avatar. The functionality was never intended by the system. May involve overhauling core code, and would be a significant project. will give so more thought

**Comment by PhilAndrecheck** [comment]
Understood about the avatar. Perhaps we can come up with a workaround like uploading a generic avatar but it's worth discussing at the meeting to tomorrow

**Comment by ToferC** [comment]
lawson.troy: I'm good with us staying away from privacy settings on the avatar. A better solution is having GCDIRECTORY with the option to sync or not sync.  Thanks @lawson.troy
