### ISSUE TITLE
Hype forum search queries take a long time, sometimes crashing sql server

### ISSUE THREAD

**Issue by Phanoix** [tbs-sct/gcconnex#83]
Queries with common substrings like " and ", " , etc which might not always be filtered by default seem to be the main cause.

**Comment by pandurx** [comment]
Has this been resolved?

**Comment by Phanoix** [comment]
We put in a filter for some very common words like 'and' from what I remember... Have we had any problems with it since?

**Comment by pandurx** [comment]
I remember that, I haven't been checking for that specific issue. But I think when someone puts in a long string to search, it also takes awhile to return.
Need to know if we want the guy from Pleio to help us with this issue.
