### ISSUE TITLE
Accessibility improvements on GCconnex

### ISSUE THREAD

**Issue by Phanoix** [tbs-sct/gcconnex#85]
1.
The base colour for GCconnex links is #0088CC. On a background colour of #FFFFFF, this results in a contrast ratio of 3.89:1 which falls below the recommended threshold of 4.5:1.
Changing the link colour to #0077CC will result in a contrast ratio of 4.66:1 while staying withing the same colour range.

2.
Also, when the mouse cursor is over most elements, there is a hover effect that is not present when the same elements get keyboard focus. 
Suggested: adding the CSS pseudoclass "focus" anywhere there is a "hover" pseudoclass used.

**Comment by Troy-Lawson** [comment]
@Phanoix @piet0024 @ethanWallace fixed in wet?

**Comment by Phanoix** [comment]
This was fixed with the redesign + wet skin.
