### ISSUE TITLE
Upgrade mods with new versions that work in Elgg 1.12

### ISSUE THREAD

**Issue by Phanoix** [tbs-sct/gcconnex#94]
This mostly involves migrating GCconnex customization patches to the new versions of the mods.

**Comment by Phanoix** [comment]
List of mods:
https://github.com/ColdTrick/widget_manager
https://github.com/tbs-sct/gcconnex/commit/9b9e73304dd1b778d19c2288fabcfd48090ea307
https://github.com/tbs-sct/gcconnex/commit/831e79494b42e8f3258d205f3a594fe5bafabd1a
https://github.com/tbs-sct/gcconnex/commit/fa2945c2fdadecb6432288a5b96364269ce39b1c

https://github.com/ColdTrick/file_tools
https://github.com/tbs-sct/gcconnex/commit/3a0b4f92314babe0b171d1aa4788ad37edfa5a3f

https://github.com/ColdTrick/group_tools
https://github.com/tbs-sct/gcconnex/commit/df64b83c85744da8226f2076352dd6135b09c354

**Comment by pandurx** [comment]
@Phanoix do you have a list of modules that aren't compatible in v1.12?

**Comment by Phanoix** [comment]
@pandurx The milestone description has a list most of the mods, excluding ones that at don't seem to need upgrades with the rest likely needing some work. I haven't checked all of them yet but you can see the ones that have been upgraded there.
